# Generated by Django 3.0.5 on 2021-03-02 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deranj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oficiul', models.CharField(choices=[('UN', 'Ungheni'), ('FL', 'Falesti'), ('GL', 'Glodeni'), ('RS', 'Riscani')], default='Oficiul', max_length=10)),
                ('nr_ordine', models.CharField(default='Nr. ordine', max_length=10)),
                ('transmis', models.CharField(default='Transmis', max_length=256)),
                ('sector', models.CharField(default='Sector', max_length=256)),
                ('instalatia', models.CharField(default='LEA-0,4kv', max_length=256)),
                ('fid_10kv', models.CharField(blank=True, max_length=256)),
                ('pt', models.CharField(blank=True, max_length=256)),
                ('fid_04kv', models.CharField(blank=True, max_length=256)),
                ('continutul', models.CharField(default='Continutuil', max_length=256)),
                ('data', models.DateField(auto_now=True)),
                ('responsabil', models.CharField(default='Responsabil', max_length=256)),
                ('starea', models.CharField(default='Neexecutat', max_length=256)),
            ],
        ),
    ]
