# Generated by Django 3.0.5 on 2021-03-23 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deconect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oficiul', models.CharField(default='Oficiul', max_length=10)),
                ('nr_ordine', models.CharField(default='Nr. ordine', max_length=10)),
                ('pt', models.CharField(blank=True, max_length=256)),
                ('fid_04kv', models.CharField(blank=True, max_length=256)),
                ('data_dec', models.CharField(blank=True, max_length=256)),
                ('data_conect', models.CharField(blank=True, max_length=256)),
                ('durata', models.CharField(blank=True, max_length=256)),
                ('cons_cas', models.CharField(blank=True, max_length=10)),
                ('cons_ec', models.CharField(blank=True, max_length=10)),
                ('total', models.CharField(blank=True, max_length=10)),
                ('cauza', models.CharField(blank=True, max_length=256)),
                ('termen', models.CharField(blank=True, max_length=64)),
            ],
        ),
    ]
