# Generated by Django 3.0.5 on 2021-03-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oficiul', models.CharField(choices=[('UN', 'Ungheni'), ('FL', 'Falesti'), ('GL', 'Glodeni'), ('RS', 'Riscani')], default='Oficiul', max_length=10)),
                ('nr_ds', models.CharField(blank=True, max_length=10)),
                ('nr_al', models.CharField(blank=True, max_length=10)),
                ('instalatia', models.CharField(default='Instalatia', max_length=256)),
                ('pt', models.CharField(blank=True, max_length=256)),
                ('localitatea', models.CharField(blank=True, max_length=256)),
                ('fid_nr', models.CharField(blank=True, max_length=256)),
                ('lucrarile', models.CharField(default='Lucrarile', max_length=256)),
                ('sef', models.CharField(default='Sef', max_length=36)),
                ('mem_ech', models.CharField(blank=True, max_length=256)),
                ('emitent', models.CharField(default='Emitent', max_length=36)),
                ('cu_dec', models.CharField(blank=True, max_length=36)),
                ('mas_teh', models.CharField(blank=True, max_length=256)),
                ('semnatura', models.CharField(default='Semnatura', max_length=36)),
                ('starea', models.CharField(default='Starea', max_length=256)),
                ('pregatire', models.CharField(default='Pregatire', max_length=256)),
                ('admitere', models.CharField(default='Admitere', max_length=256)),
                ('terminare', models.CharField(default='Terminare', max_length=256)),
                ('link', models.CharField(blank=True, max_length=256)),
            ],
        ),
    ]
