# Generated by Django 3.0.5 on 2021-01-28 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oficiul', models.CharField(max_length=10)),
                ('instalatia', models.CharField(max_length=36)),
                ('localitatea', models.CharField(max_length=36)),
            ],
        ),
    ]
